### ISSUE TITLE
Segment Explorer has blank map

### ISSUE THREAD

**Issue by mathead** [liskin/strava-map-switcher#1]
Hi!
First of all, thanks a lot for this plugin. I love strava combined with mtbmap!

Unfortunately, I stumbled upon an issue when I try to open the segment explorer. The map blinks and turns blank as seen here:
![capture](https://cloud.githubusercontent.com/assets/3639083/23836168/63492128-0774-11e7-9b95-07e0823f8836.PNG)

I used Firefox 51.0.1, but it doesn't seem to work in Chrome as well.

Thanks!

**Comment by liskin** [comment]
There's been a change on Strava's side. I had a quick look and should be possible to fix this somehow, I'll try to get to it sometime next week.

**Comment by liskin** [comment]
This should be fixed in https://github.com/liskin/strava-map-switcher/releases/tag/v0.8
