### ISSUE TITLE
Does not work with current Chrome

### ISSUE THREAD

**Issue by gloverb103** [liskin/strava-map-switcher#12]
Map Switcher is not currently working with Chrome Version 83.0.4103.61

**Comment by liskin** [comment]
Can you please elaborate on the “not working” part? It's working well for me with that exact Chrome version.

**Comment by gloverb103** [comment]
Yes, I have added the extension and authorized it’s use for Chrome (works
fine on Firefox) but there is no option to view OSM or any other maps when
selecting the dropdown menu on Strava. Only Terrain and Sattelite are
options currently available.

Also, is there a way to switch the base map to OSM when using the new route
builder? I cannot seem to find this option/dropdown menu on that page.
[image: Screen Shot 2020-05-26 at 8.45.17 AM.png]

**Comment by liskin** [comment]
That's weird. Are you using the most recent version?
Are there any errors in DevTools console?
Switching maps in route builder should work as well, see here: https://user-images.githubusercontent.com/300342/82727675-4447ea00-9cec-11ea-8109-334b83e5a096.png

Oh and if you've tried to attach an image, it didn't get through.

**Comment by gloverb103** [comment]
I just added the extension this morning so it should be current. There are
errors showing in the devtools, I’ve attached a screenshot this time.

**Comment by liskin** [comment]
I'm afraid github isn't picking up any images you attach via e-mail. :-(

**Comment by gloverb103** [comment]
Here is the text of the error on devtools for chrome.. looks like a cookie
issue?

Uncaught DOMException: Failed to set the 'stravaMapSwitcherVersion'
property on 'Storage': Setting the value of 'stravaMapSwitcherVersion'
exceeded the quota.
    at chrome-extension://djcheclpmmkcdkjcenfamalobdenmici/inject.js:14:40
3513954654:1 A cookie associated with a cross-site resource at
http://mapbox.com/ was set without the `SameSite` attribute. A future
release of Chrome will only deliver cookies with cross-site requests if
they are set with `SameSite=None` and `Secure`. You can review cookies in
developer tools under Application>Storage>Cookies and see more details at
https://www.chromestatus.com/feature/5088147346030592 and
https://www.chromestatus.com/feature/5633521622188032.

**Comment by liskin** [comment]
Those two are probably unrelated. So the relevant part is just this:

```
Uncaught DOMException: Failed to set the 'stravaMapSwitcherVersion'
property on 'Storage': Setting the value of 'stravaMapSwitcherVersion'
exceeded the quota.
```

It seems your `window.localStorage` for strava.com is full (the quota is something like 5MB or 10MB, and strava-map-switcher only uses a few dozens bytes out of that). I can try to add try/catch around all localStorage accesses, but then some features like remembering the preferred map wouldn't work. Perhaps you can clear your local storage, or use the DevTools to peek what's filling the quota and drop just that?

**Comment by gloverb103** [comment]
Thank you so much I’ll give that a try

**Comment by liskin** [comment]
Did you get it working? Can we close this issue?

**Comment by gloverb103** [comment]
Yes! I’m sorry, I meant to get back to you. I followed your advice and it
worked great. Thank you for your help!

Bryan
