### ISSUE TITLE
Map Switcher breaks Personal Heatmaps

### ISSUE THREAD

**Issue by nixxcz** [liskin/strava-map-switcher#13]
When Map Switcher is enabled, Personal Heatmaps (subscription feature) won't load.

Steps to reproduce:
1. Go to https://www.strava.com/athlete/heatmaps (paid Strava subscription required)
2. Generate a personal heatmap
3. Visit the heatmap (e.g. https://www.strava.com/athletes/{id}/heatmaps/{key})
5. The heatmap won't load. JavaScript console displays the following errors:
```
You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.
```
```
Unchecked runtime.lastError: The message port closed before a response was received.
```
6. When Map Switcher is disabled, the heatmap loads and error messages are not displayed

**Comment by liskin** [comment]
I can't reproduce this (I do have trial membership and a personal heatmap but the extension doesn't break it) but I'll try to fix this somehow and let you test it. Will you be able to test a patch locally?

**Comment by nixxcz** [comment]
Sure, I'll be happy to test. It puzzles me that you can't repro. I'm thinking maybe it could be some interaction between AdBlock, Elevate extension for Strava or some other extension I'm using. I'm not at my PC now to test.

**Comment by liskin** [comment]
Yeah, interaction with another extension would be my first guess, too.
(I won't get to attempting to fix this until Tuesday.)

**Comment by nixxcz** [comment]
It seems there's some sort of race condition when loading a Personal Heatmap. When I disable all extensions, the Personal Heatmap seems to load fine each time. When I enable strava-map-switcher and keep hitting F5 (in Chrome), the map sometimes does't load (and sometimes it does).

**Comment by liskin** [comment]
Tried it again today and using shift-reload I could reproduce it fairly often. Pushing a fix.

**Comment by mefjuu** [comment]
This issue still occurs. At least on StrViewer extension. that is based on strava-map-switcher (?).

**Comment by liskin** [comment]
> This issue still occurs. At least on StrViewer extension that is based on strava-map-switcher (as far as the docs say).

"based on" in this context really just means they took my code. There's absolutely nothing I can do here to fix any problems you're having with StrViewer.
