### ISSUE TITLE
Route not visible on map since using the extension

### ISSUE THREAD

**Issue by dominiquevilain** [liskin/strava-map-switcher#3]
In Firefox 57, the route fails to display over the selected map. In the main flow view, one can see the route preview, but on the activity page, the route is not displayed.

I've tried to remove the extension and the problem remains. 

Before i installed the extension, the routes were displayed correctly and in FF Dev. Edition (in which i never installed the extension), they are displayed correctly aswell.

**Comment by liskin** [comment]
It works just fine for me in Firefox 57. Can you perhaps post a screenshot?

**Comment by dominiquevilain** [comment]
First Screen show the map from the flow view
<img width="543" alt="capture d ecran 2017-11-17 a 16 14 00" src="https://user-images.githubusercontent.com/708778/32954141-90c7c35e-cbb2-11e7-8cc5-d1c31fafc5e3.png">

Second screen shows the map on the activity view with Strava Map Switcher. The details are gone.
<img width="1053" alt="capture d ecran 2017-11-17 a 16 14 22" src="https://user-images.githubusercontent.com/708778/32954197-ba755518-cbb2-11e7-8dd6-571fd86867f8.png">

Thired screen show the map on the activity view in FF Dev. (SMS never installed). Everything is fine.
![capture d ecran 2017-11-17 a 16 15 06](https://user-images.githubusercontent.com/708778/32954249-d9b216e6-cbb2-11e7-8f9a-816e576b897f.png)

**Comment by dominiquevilain** [comment]
I’ve found the reason why the routes where not displaying… Sorry for the inconvenience. The reason was not the SMS extension but another one, Ghostery. I did install both of them at the same moment, and thought that the Strava extension was responsible for the problems with the Strava site. Now, it works great (i've fixed a setting in Ghostery), so, thanks for the extension !
